/* Test we correctly switch to longer chains. */
#include <ccan/asort/asort.h>
#include <time.h>
#include <assert.h>

static time_t fake_time;
static time_t my_time(time_t *p)
{
	if (p)
		*p = fake_time;
	return fake_time;
}

#define main generate_main
#define time my_time

#include "../generate.c"
#include "../timestamp.c"
#undef main
#undef time
#include "helper_key.h"
#include "helper_gateway_key.h"
#include "../hash_block.c"
#include "../shadouble.c"
#include "../difficulty.c"
#include "../merkle_txs.c"
#include "../merkle_recurse.c"
#include "../merkle_hashes.c"
#include "../tx_cmp.c"
#include "../marshal.c"
#include "../hash_tx.c"
#include "../create_tx.c"
#include "../check_block.c"
#include "../block.c"
#include "../prev_txhashes.c"
#include "../minimal_log.c"
#include "../signature.c"
#include "../txhash.c"
#include "../inputhash.c"
#include "../shard.c"
#include "../chain.c"
#include "../check_tx.c"
#include "../features.c"
#include "../tal_packet.c"
#include "../gateways.c"
#include "../state.c"
#include "../pseudorand.c"
#include "../create_refs.c"
#include "../tx.c"
#include "../block_shard.c"
#include "../proof.c"
#include "easy_genesis.c"

/* AUTOGENERATED MOCKS START */
/* Generated stub for check_tx_refs */
enum ref_ecode check_tx_refs(struct state *state,
			     const struct block *block,
			     const union protocol_tx *tx,
			     const struct protocol_input_ref *refs,
			     unsigned int *bad_ref,
			     struct block **block_referred_to) { fprintf(stderr, "check_tx_refs called!\n"); abort(); }
/* Generated stub for complain_bad_amount */
void complain_bad_amount(struct state *state,
			 struct block *block,
			 const struct protocol_proof *proof,
			 const union protocol_tx *tx,
			 const struct protocol_input_ref *refs,
			 const union protocol_tx *intx[]) { fprintf(stderr, "complain_bad_amount called!\n"); abort(); }
/* Generated stub for complain_bad_input */
void complain_bad_input(struct state *state,
			struct block *block,
			const struct protocol_proof *proof,
			const union protocol_tx *tx,
			const struct protocol_input_ref *refs,
			unsigned int bad_input,
			const union protocol_tx *intx) { fprintf(stderr, "complain_bad_input called!\n"); abort(); }
/* Generated stub for complain_bad_input_ref */
void complain_bad_input_ref(struct state *state,
			    struct block *block,
			    const struct protocol_proof *proof,
			    const union protocol_tx *tx,
			    const struct protocol_input_ref *refs,
			    unsigned int bad_refnum,
			    const struct block *block_referred_to) { fprintf(stderr, "complain_bad_input_ref called!\n"); abort(); }
/* Generated stub for complain_doublespend */
void complain_doublespend(struct state *state,
			  struct block *block1,
			  u32 input1,
			  const struct protocol_proof *proof1,
			  const union protocol_tx *tx1,
			  const struct protocol_input_ref *refs1,
			  struct block *block2,
			  u32 input2,
			  const struct protocol_proof *proof2,
			  const union protocol_tx *tx2,
			  const struct protocol_input_ref *refs2) { fprintf(stderr, "complain_doublespend called!\n"); abort(); }
/* Generated stub for todo_add_get_tx */
void todo_add_get_tx(struct state *state,
		     const struct protocol_double_sha *tx) { fprintf(stderr, "todo_add_get_tx called!\n"); abort(); }
/* Generated stub for todo_add_get_tx_in_block */
void todo_add_get_tx_in_block(struct state *state,
			      const struct protocol_double_sha *block,
			      u16 shardnum, u8 txoff) { fprintf(stderr, "todo_add_get_tx_in_block called!\n"); abort(); }
/* Generated stub for todo_forget_about_block */
void todo_forget_about_block(struct state *state,
			     const struct protocol_double_sha *block) { fprintf(stderr, "todo_forget_about_block called!\n"); abort(); }
/* Generated stub for wake_peers */
void wake_peers(struct state *state) { fprintf(stderr, "wake_peers called!\n"); abort(); }
/* AUTOGENERATED MOCKS END */

/* FIXME: Check this value! */
static unsigned int block_txs_moved;

void steal_pending_txs(struct state *state,
		       const struct block *old,
		       const struct block *new)
{
	block_txs_moved++;
}

void restart_generating(struct state *state)
{
}

void todo_add_get_shard(struct state *state,
			const struct protocol_double_sha *block,
			u16 shardnum)
{
}

struct log *new_log(const tal_t *ctx,
		    const struct log *parent,
		    const char *prefix,
		    enum log_level printlevel, size_t max_mem)
{
	return NULL;
}

struct pending_block *new_pending_block(struct state *state)
{
	return NULL;
}

void logv(struct log *log, enum log_level level, const char *fmt, va_list ap)
{
}

void log_to_file(int fd, const struct log *log)
{
}

int main(int argc, char *argv[])
{
	struct state *s;
	struct working_block *w;
	u8 *prev_txhashes;
	unsigned int i, j;
	struct block *b[5], *b_alt[3], *prev, *prev2;
	enum protocol_ecode e;
	struct protocol_double_sha sha;

	pseudorand_init();
	s = new_state(true);
	fake_time = le32_to_cpu(genesis_tlr.timestamp) + 1;
	prev = &genesis;
		
	/* Generate chain of three blocks. */
	for (i = 0; i < 3; i++) {
		prev_txhashes = make_prev_txhashes(s, prev, helper_addr(1));
		w = new_working_block(s, 0x1ffffff0,
				      prev_txhashes, tal_count(prev_txhashes),
				      le32_to_cpu(prev->hdr->depth) + 1,
				      next_shard_order(prev),
				      &prev->sha, helper_addr(1));
		for (j = 0; !solve_block(w); j++);
		fake_time++;
		e = check_block_header(s, &w->hdr, w->shard_nums,
				       w->merkles, w->prev_txhashes,
				       &w->tailer, &prev2, &sha);
		assert(e == PROTOCOL_ECODE_NONE);
		assert(prev2 == prev);

		b[i] = block_add(s, prev, &sha, &w->hdr, w->shard_nums,
				 w->merkles, w->prev_txhashes, &w->tailer);

		assert(tal_count(s->longest_chains) == 1);
		assert(s->longest_chains[0] == b[i]);
		assert(tal_count(s->longest_knowns) == 1);
		assert(s->longest_knowns[0] == b[i]);
		assert(s->preferred_chain == b[i]);
		prev = b[i];
	}

	/* Now generate an alternate chain of two blocks, from b[0]. */
	prev = b[0];
	for (i = 0; i < 2; i++) {
		prev_txhashes = make_prev_txhashes(s, prev, helper_addr(2));
		w = new_working_block(s, 0x1ffffff0,
				      prev_txhashes, tal_count(prev_txhashes),
				      le32_to_cpu(prev->hdr->depth) + 1,
				      next_shard_order(prev),
				      &prev->sha, helper_addr(2));
		for (j = 0; !solve_block(w); j++);
		fake_time++;
		e = check_block_header(s, &w->hdr, w->shard_nums,
				       w->merkles, w->prev_txhashes,
				       &w->tailer, &prev2, &sha);
		assert(e == PROTOCOL_ECODE_NONE);
		assert(prev2 == prev);
		b_alt[i] = block_add(s, prev, &sha,
				     &w->hdr, w->shard_nums, w->merkles,
				     w->prev_txhashes, &w->tailer);
		if (i == 0) {
			assert(tal_count(s->longest_chains) == 1);
			assert(tal_count(s->longest_knowns) == 1);
		} else {
			/* Second block brings us equal. */
			assert(tal_count(s->longest_chains) == 2);
			assert(tal_count(s->longest_knowns) == 2);
			assert(s->longest_chains[1] == b_alt[1]);
			assert(s->longest_knowns[1] == b_alt[1]);
		}
		assert(s->longest_chains[0] == b[2]);
		assert(s->longest_knowns[0] == b[2]);
		assert(s->preferred_chain == b[2]);
		prev = b_alt[i];
	}

	/* Now make alternate chain overtake first chain. */
	prev_txhashes = make_prev_txhashes(s, prev, helper_addr(2));
	w = new_working_block(s, 0x1ffffff0,
			      prev_txhashes, tal_count(prev_txhashes),
			      le32_to_cpu(prev->hdr->depth) + 1,
			      next_shard_order(prev),
			      &prev->sha, helper_addr(2));
	for (j = 0; !solve_block(w); j++);
	fake_time++;
	e = check_block_header(s, &w->hdr, w->shard_nums, w->merkles,
			       w->prev_txhashes, &w->tailer, &prev2, &sha);
	assert(e == PROTOCOL_ECODE_NONE);
	assert(prev2 == prev);

	b_alt[2] = block_add(s, prev, &sha, &w->hdr, w->shard_nums, w->merkles,
			     w->prev_txhashes, &w->tailer);

	assert(tal_count(s->longest_chains) == 1);
	assert(s->longest_chains[0] == b_alt[2]);
	assert(tal_count(s->longest_knowns) == 1);
	assert(s->longest_knowns[0] == b_alt[2]);
	assert(s->preferred_chain == b_alt[2]);

	/* Now make first chain equal again. */
	prev = b[2];
	prev_txhashes = make_prev_txhashes(s, prev, helper_addr(1));
	w = new_working_block(s, 0x1ffffff0,
			      prev_txhashes, tal_count(prev_txhashes),
			      le32_to_cpu(prev->hdr->depth) + 1,
			      next_shard_order(prev),
			      &prev->sha, helper_addr(1));
	for (j = 0; !solve_block(w); j++);
	fake_time++;
	e = check_block_header(s, &w->hdr, w->shard_nums, w->merkles,
			       w->prev_txhashes, &w->tailer, &prev2, &sha);
	assert(e == PROTOCOL_ECODE_NONE);
	assert(prev2 == prev);

	b[3] = block_add(s, prev, &sha,
			 &w->hdr, w->shard_nums, w->merkles,
			 w->prev_txhashes, &w->tailer);

	assert(tal_count(s->longest_chains) == 2);
	assert(tal_count(s->longest_knowns) == 2);
	assert(s->longest_chains[0] == b_alt[2]);
	assert(s->longest_knowns[0] == b_alt[2]);
	assert(s->longest_chains[1] == b[3]);
	assert(s->longest_knowns[1] == b[3]);
	assert(s->preferred_chain == b_alt[2]);

	/* Now overtake. */
	prev = b[3];
	prev_txhashes = make_prev_txhashes(s, prev, helper_addr(1));
	w = new_working_block(s, 0x1ffffff0,
			      prev_txhashes, tal_count(prev_txhashes),
			      le32_to_cpu(prev->hdr->depth) + 1,
			      next_shard_order(prev),
			      &prev->sha, helper_addr(1));
	for (j = 0; !solve_block(w); j++);
	fake_time++;
	e = check_block_header(s, &w->hdr, w->shard_nums, w->merkles,
			       w->prev_txhashes, &w->tailer, &prev2, &sha);
	assert(e == PROTOCOL_ECODE_NONE);
	assert(prev2 == prev);
	b[4] = block_add(s, prev, &sha, &w->hdr, w->shard_nums, w->merkles,
			 w->prev_txhashes, &w->tailer);

	assert(tal_count(s->longest_chains) == 1);
	assert(s->longest_chains[0] == b[4]);
	assert(tal_count(s->longest_knowns) == 1);
	assert(s->longest_knowns[0] == b[4]);
	assert(s->preferred_chain == b[4]);

	tal_free(s);
	return 0;
}
