#include "../chain.c"
#include "../state.c"
#include "../timeout.c"
#include "../block.c"
#include "../pseudorand.c"
#include "../minimal_log.c"
#include "../difficulty.c"
#include "../block_shard.c"
#include "../tx.c"
#include "../features.c"
#include "easy_genesis.c"
#include "named_blocks.c"

/* AUTOGENERATED MOCKS START */
/* Generated stub for block_to_pending */
void block_to_pending(struct state *state, const struct block *block)
{ fprintf(stderr, "block_to_pending called!\n"); abort(); }
/* Generated stub for check_prev_txhashes */
bool check_prev_txhashes(struct state *state, const struct block *block,
			 const struct block **bad_prev,
			 u16 *bad_shard)
{ fprintf(stderr, "check_prev_txhashes called!\n"); abort(); }
/* Generated stub for check_proof */
bool check_proof(const struct protocol_proof *proof,
		 const struct block *b,
		 const union protocol_tx *tx,
		 const struct protocol_input_ref *refs)
{ fprintf(stderr, "check_proof called!\n"); abort(); }
/* Generated stub for check_tx */
enum protocol_ecode check_tx(struct state *state, const union protocol_tx *tx,
			     const struct block *inside_block)
{ fprintf(stderr, "check_tx called!\n"); abort(); }
/* Generated stub for check_tx_inputs */
enum input_ecode check_tx_inputs(struct state *state,
				 const struct block *block,
				 const struct txhash_elem *me,
				 const union protocol_tx *tx,
				 unsigned int *bad_input_num)
{ fprintf(stderr, "check_tx_inputs called!\n"); abort(); }
/* Generated stub for complain_bad_prev_txhashes */
void complain_bad_prev_txhashes(struct state *state,
				struct block *block,
				const struct block *bad_prev,
				u16 bad_prev_shard)
{ fprintf(stderr, "complain_bad_prev_txhashes called!\n"); abort(); }
/* Generated stub for from_hex */
bool from_hex(const char *str, size_t slen, void *buf, size_t bufsize)
{ fprintf(stderr, "from_hex called!\n"); abort(); }
/* Generated stub for hash_tx */
void hash_tx(const union protocol_tx *tx, struct protocol_tx_id *txid)
{ fprintf(stderr, "hash_tx called!\n"); abort(); }
/* Generated stub for hash_tx_and_refs */
void hash_tx_and_refs(const union protocol_tx *tx,
		      const struct protocol_input_ref *refs,
		      struct protocol_txrefhash *txrefhash)
{ fprintf(stderr, "hash_tx_and_refs called!\n"); abort(); }
/* Generated stub for inputhash_hashfn */
size_t inputhash_hashfn(const struct inputhash_key *key)
{ fprintf(stderr, "inputhash_hashfn called!\n"); abort(); }
/* Generated stub for inputhash_keyof */
const struct inputhash_key *inputhash_keyof(const struct inputhash_elem *ie)
{ fprintf(stderr, "inputhash_keyof called!\n"); abort(); }
/* Generated stub for json_add_address */
void json_add_address(struct json_result *result, const char *fieldname,
		      bool test_net,  const struct protocol_address *addr)
{ fprintf(stderr, "json_add_address called!\n"); abort(); }
/* Generated stub for json_add_block_id */
void json_add_block_id(struct json_result *result, const char *fieldname,
		       const struct protocol_block_id *id)
{ fprintf(stderr, "json_add_block_id called!\n"); abort(); }
/* Generated stub for json_add_double_sha */
void json_add_double_sha(struct json_result *result, const char *fieldname,
			 const struct protocol_double_sha *sha)
{ fprintf(stderr, "json_add_double_sha called!\n"); abort(); }
/* Generated stub for json_add_hex */
void json_add_hex(struct json_result *result, const char *fieldname,
		  const void *data, size_t len)
{ fprintf(stderr, "json_add_hex called!\n"); abort(); }
/* Generated stub for json_add_num */
void json_add_num(struct json_result *result, const char *fieldname,
		  unsigned int value)
{ fprintf(stderr, "json_add_num called!\n"); abort(); }
/* Generated stub for json_add_tx_id */
void json_add_tx_id(struct json_result *result, const char *fieldname,
		    const struct protocol_tx_id *id)
{ fprintf(stderr, "json_add_tx_id called!\n"); abort(); }
/* Generated stub for json_array_end */
void json_array_end(struct json_result *ptr)
{ fprintf(stderr, "json_array_end called!\n"); abort(); }
/* Generated stub for json_array_start */
void json_array_start(struct json_result *ptr, const char *fieldname)
{ fprintf(stderr, "json_array_start called!\n"); abort(); }
/* Generated stub for json_get_params */
void json_get_params(const char *buffer, const jsmntok_t param[], ...)
{ fprintf(stderr, "json_get_params called!\n"); abort(); }
/* Generated stub for json_object_end */
void json_object_end(struct json_result *ptr)
{ fprintf(stderr, "json_object_end called!\n"); abort(); }
/* Generated stub for json_object_start */
void json_object_start(struct json_result *ptr, const char *fieldname)
{ fprintf(stderr, "json_object_start called!\n"); abort(); }
/* Generated stub for json_tok_contents */
const char *json_tok_contents(const char *buffer, const jsmntok_t *t)
{ fprintf(stderr, "json_tok_contents called!\n"); abort(); }
/* Generated stub for json_tok_len */
int json_tok_len(const jsmntok_t *t)
{ fprintf(stderr, "json_tok_len called!\n"); abort(); }
/* Generated stub for json_tok_number */
bool json_tok_number(const char *buffer, const jsmntok_t *tok,
		     unsigned int *num)
{ fprintf(stderr, "json_tok_number called!\n"); abort(); }
/* Generated stub for log_to_file */
void log_to_file(int fd, const struct log_record *lr)
{ fprintf(stderr, "log_to_file called!\n"); abort(); }
/* Generated stub for logv */
void logv(struct log *log, enum log_level level, const char *fmt, va_list ap)
{ fprintf(stderr, "logv called!\n"); abort(); }
/* Generated stub for make_prev_blocks */
void make_prev_blocks(const struct block *prev,
		      struct protocol_block_id prevs[PROTOCOL_NUM_PREV_IDS])
{ fprintf(stderr, "make_prev_blocks called!\n"); abort(); }
/* Generated stub for merkle_txs */
void merkle_txs(const struct block_shard *shard,
		struct protocol_double_sha *merkle)
{ fprintf(stderr, "merkle_txs called!\n"); abort(); }
/* Generated stub for refresh_peer_cache */
void refresh_peer_cache(struct state *state)
{ fprintf(stderr, "refresh_peer_cache called!\n"); abort(); }
/* Generated stub for todo_forget_about_block */
void todo_forget_about_block(struct state *state,
			     const struct protocol_block_id *block)
{ fprintf(stderr, "todo_forget_about_block called!\n"); abort(); }
/* Generated stub for wake_peers */
void wake_peers(struct state *state)
{ fprintf(stderr, "wake_peers called!\n"); abort(); }
/* AUTOGENERATED MOCKS END */

struct pending_block *new_pending_block(struct state *state)
{
	return talz(state, struct pending_block);
}

void save_block(struct state *state, struct block *new)
{
}

void check_block(struct state *state, const struct block *block, bool all)
{
}

void seek_detached_blocks(struct state *state, 
			  const struct block *block)
{
}

int main(void)
{
	struct state *state;
	const struct block **bests;
	struct protocol_address dummy = { { 0 } };

	pseudorand_init();
	state = new_state(true);

	/* genesis -> block1-0 ... block1-10. */
	create_chain(state, &genesis, "block1", &dummy,
		     PROTOCOL_INITIAL_SHARD_ORDER, 10, true);

	/* Simple step_towards test. */
	assert(step_towards(&genesis, strmap_get(&blockmap, "block1-5"))
	       == strmap_get(&blockmap, "block1-0"));

	assert(step_towards(strmap_get(&blockmap, "block1-5"), &genesis)
	       == NULL);

	/* block1-5 -> block2-0 ... block2-9. */
	create_chain(state, strmap_get(&blockmap, "block1-5"), "block2",
		     &dummy, PROTOCOL_INITIAL_SHARD_ORDER, 10, true);

	/* step_towards working over a fork. */
	assert(step_towards(strmap_get(&blockmap, "block1-9"),
			    strmap_get(&blockmap, "block2-9"))
	       == strmap_get(&blockmap, "block2-0"));

	assert(step_towards(strmap_get(&blockmap, "block2-9"),
			    strmap_get(&blockmap, "block1-9"))
	       == strmap_get(&blockmap, "block1-6"));

	/* step_towards goes to destination. */
	assert(step_towards(strmap_get(&blockmap, "block2-9"),
			    strmap_get(&blockmap, "block1-6"))
	       == strmap_get(&blockmap, "block1-6"));

	/* Test find_longest_descendents */
	bests = tal_arr(state, const struct block *, 1);
	bests[0] = &genesis;
	find_longest_descendents(&genesis, &bests);
	assert(tal_count(bests) == 1);
	assert(bests[0] == strmap_get(&blockmap, "block2-9"));

	/* Extend it by one */
	add_next_block(state, cast_const(struct block *, bests[0]),
		       tal_strdup(state, "block2-10"), 0,
		       PROTOCOL_INITIAL_SHARD_ORDER, &dummy);
	find_longest_descendents(&genesis, &bests);
	assert(tal_count(bests) == 1);
	assert(bests[0] == strmap_get(&blockmap, "block2-10"));

	/* Now create another one. */
	bests[0] = &genesis;
	add_next_block(state, strmap_get(&blockmap, "block2-9"),
		       tal_strdup(state, "block2-10b"),
		       0, PROTOCOL_INITIAL_SHARD_ORDER, &dummy);
	find_longest_descendents(&genesis, &bests);
	assert(tal_count(bests) == 2);
	assert(bests[0] == strmap_get(&blockmap, "block2-10")
	       && bests[1] == strmap_get(&blockmap, "block2-10b"));

	strmap_clear(&blockmap);
	tal_free(state);
	return 0;
}
