default-test-standalone:
	@echo Run make from top dir. >&2 && exit 1

test-clean: test-standalone-clean
test-distclean: test-standalone-distclean

test-standalone-clean:
	$(RM) -r test/standalone/pettycoin-* test/standalone/addresses

test-standalone-distclean:

